CREATE TABLE IF NOT EXISTS `SQL_PREFIX_modules_commandes` (
  `ID` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `Login` varchar(30) NOT NULL COMMENT 'Login de l''acheteur',
  `LoginV` varchar(30) NOT NULL COMMENT 'login du vendeur',
  `Items` text COMMENT 'Items commandés',
  `TypePaiement` text NOT NULL,
  `Paiement` text NOT NULL,
  `DateCreated` datetime DEFAULT NULL,
  `DateLivraison` datetime DEFAULT NULL,
  `DatePaiement` datetime DEFAULT NULL,
  `CoordLivraison` varchar(128) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `Login` (`Login`),
  KEY `Founisseur` (`LoginV`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=17 ;

CREATE TABLE IF NOT EXISTS `SQL_PREFIX_Modules_Template` (
  `ID` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `Nom` varchar(128) NOT NULL,
  `Abreviation` varchar(128) DEFAULT NULL,
  `Description` text,
  `Categorie` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `Taille` smallint(5) unsigned DEFAULT NULL,
  `PAChasseur` smallint(5) unsigned DEFAULT NULL,
  `PAGVG` smallint(5) unsigned DEFAULT NULL,
  `URLIcone` varchar(250) DEFAULT NULL,
  `URLMedium` varchar(250) DEFAULT NULL,
  `URLImage` varchar(250) DEFAULT NULL,
  `Temps` time DEFAULT '00:00:00',
  `Titane` int(10) unsigned DEFAULT NULL,
  `Cuivre` int(10) unsigned DEFAULT NULL,
  `Fer` int(10) unsigned DEFAULT NULL,
  `Aluminium` int(10) unsigned DEFAULT NULL,
  `Mercure` int(10) unsigned DEFAULT NULL,
  `Silicium` int(10) unsigned DEFAULT NULL,
  `Uranium` int(10) unsigned DEFAULT NULL,
  `Krypton` int(10) unsigned DEFAULT NULL,
  `Azote` int(10) unsigned DEFAULT NULL,
  `Hydrogene` int(10) unsigned DEFAULT NULL,
  `PropImpulsion` int(10) unsigned DEFAULT NULL,
  `PropWarp` int(10) unsigned DEFAULT NULL,
  `PropConsommation` decimal(2,1) unsigned DEFAULT NULL,
  `ArmType` tinyint(3) unsigned DEFAULT NULL,
  `ArmDegat` smallint(5) unsigned DEFAULT NULL,
  `ArmManiabilite` smallint(5) unsigned DEFAULT NULL,
  `ProtType` tinyint(3) unsigned DEFAULT NULL,
  `ProtChasseur` smallint(5) unsigned DEFAULT NULL,
  `ProtGVG` smallint(5) unsigned DEFAULT NULL,
  `EquipType` tinyint(3) unsigned DEFAULT NULL,
  `EquipNiv` int(10) unsigned DEFAULT NULL,
  `ChassType` tinyint(3) unsigned DEFAULT NULL,
  `ChassPA` smallint(5) unsigned DEFAULT NULL,
  `ChassCellules` smallint(5) unsigned DEFAULT NULL,
  `ChassStructure` smallint(5) unsigned DEFAULT NULL,
  `ChassCarburant` int(10) unsigned DEFAULT NULL,
  `ChassImpulsion` decimal(10,2) unsigned DEFAULT NULL,
  `ChassWarp` decimal(10,2) unsigned DEFAULT NULL,
  `ChassManiabilite` smallint(5) unsigned DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `Nom` (`Nom`),
  KEY `Abreviation` (`Abreviation`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=169 ;

CREATE TABLE IF NOT EXISTS `SQL_PREFIX_Modules_Users` (
  `Login` varchar(30) NOT NULL,
  `Module_ID` bigint(20) unsigned NOT NULL,
  `Modifier` smallint(5) NOT NULL DEFAULT '0',
  PRIMARY KEY (`Login`,`Module_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `SQL_PREFIX_Users_Config` (
  `Login` varchar(30) NOT NULL,
  `DateCreated` datetime DEFAULT NULL,
  `DateLast` datetime DEFAULT NULL,
  `Modifier` smallint(5) DEFAULT '0',
  `ListSort` tinyint(3) DEFAULT '0',
  `ActivatedSort` tinyint(1) DEFAULT '0',
  `CommerceType` tinyint(3) DEFAULT '0',
  `ChassisSecret` tinyint(3) DEFAULT '1',
  `Paiement` smallint(2) unsigned DEFAULT '1',
  `Planetes` smallint(2) unsigned DEFAULT '0',
  PRIMARY KEY (`Login`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;